version: '3.8'
services:
  main:
    container_name: VueServer
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
      - 5173:5173